name: Setup repository
description: "Setup repository for CI/CD workflows"

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@v4
    - uses: actions/setup-node@v6
      with:
        cache: yarn
        registry-url: https://registry.npmjs.org
